name: Build Job
on:
    push:
        branches: [ main ]
    
    pull_request:
        branches: [ "main", "feature" ]
    
    workflow_dispatch:
    
    schedule:
        - cron: '10 13 * * 1-5' # Runs every day at midnight

env:
    ECR_REPOSITORY: 'vprofile-application'

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Code checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Maven Build
              run: mvn install

            - name: Upload Build Artifact
              uses: actions/upload-artifact@v4
              with:
                name: vprofile-app
                path: target/*.war
            - name: Notify Build Fails
              if: failure()
              run: echo "Build failed! Please check the logs for details."
    

    Testing:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Code checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Run tests on main branch
              if: github.ref == 'refs/heads/main'
              run: mvn test

            - name: Checstyle
              if: github.ref == 'refs/heads/main'
              run: mvn checkstyle:check

            - name: Run tests on feature branch
              if: github.ref == 'refs/heads/feature'
              run: echo "Skipping unit tests and code analysis"
    
    Security-Scan:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Code checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Run Trivy Security Scan
              uses: aquasecurity/trivy-action@master
              with:
                scan-type: 'fs'
                scan-ref: '.'
                format: json
                exit-code: '0'
                vuln-type: 'os,library'
                output: 'trivy-report.json'
            
            - name: Upload Trivy scan results as artifact
              uses: actions/upload-artifact@v4
              with:
                name: trivy-scan-results
                path: trivy-results.json


    BUILD_AND_PUBLISH:
        name: BUILD AND PUBLISH
        runs-on: ubuntu-latest
        environment: production
        needs: [build, Testing, Security-Scan]
        if: github.ref == 'refs/heads/main'
        steps:
            - name: Code checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ vars.AWS_REGION }}

            - name: Login to Amazon ECR
              id: login-ecr    
              uses: aws-actions/amazon-ecr-login@v2
              
            - name: Build, tag, and push Docker image to Amazon ECR
              id: build-imgae
              env:
                ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
                IMAGE_TAG: ${{ github.sha }}
              run: |
                docker build -f Docker-files/app/multistage/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
                docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG    
                echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
            
            
        


              


